module-name: kyma-environment-broker
kind: kcp
rc-tag: 1.22.6
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-broker:1.22.6
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-deprovision-retrigger-job:1.22.6
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-runtime-reconciler:1.22.6
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-expirator-job:1.22.6
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-subaccount-cleanup-job:1.22.6
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-subaccount-sync:1.22.6
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-broker-globalaccounts:1.22.6
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-broker-schema-migrator:1.22.6
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-service-binding-cleanup-job:1.22.6
mend:
  language: golang-mod
  exclude:
    - "**/*_test.go"
    - "**/testing/**"
    - "**/automock/**"
    - "**/*fake*.go"
    - "**/*mock*.go"
checkmarx-one:
  preset: go-default
  exclude:
    - "**/*_test.go"
    - "**/testing/**"
    - "**/automock/**"
    - "**/*fake*.go"
    - "**/*mock*.go"
