module-name: kyma-environment
rc-tag: 0.0.2
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-broker:0.0.2
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
    - "testing/**"
