module-name: kyma-environment-broker
kind: kcp
rc-tag: 0.0.401
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-broker:0.0.401
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-deprovision-retrigger-job:0.0.401
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-runtime-reconciler:0.0.401
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-expirator-job:0.0.401
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-subaccount-cleanup-job:0.0.401
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-subaccount-sync:0.0.401
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-broker-globalaccounts:0.0.401
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-broker-schema-migrator:0.0.401
  - europe-docker.pkg.dev/kyma-project/prod/kyma-environment-service-binding-cleanup-job:0.0.401
mend:
  language: golang-mod
  exclude:
    - "**/*_test.go"
    - "**/testing/**"
    - "**/automock/**"
    - "**/*fake*.go"
    - "**/*mock*.go"
checkmarx-one:
  preset: go-default
  exclude:
    - "**/*_test.go"
    - "**/testing/**"
    - "**/automock/**"
    - "**/*fake*.go"
    - "**/*mock*.go"
