apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kyma-env-broker.fullname" . }}
  labels:
{{ include "kyma-env-broker.labels" . | indent 4 }}
data:
  trialRegionMapping.yaml: |-
{{- with .Values.trialRegionsMapping }}
{{ tpl . $ | indent 4 }}
{{- end }}
  skrOIDCDefaultValues.yaml: |-
{{- with .Values.skrOIDCDefaultValues }}
{{ tpl . $ | indent 4 }}
{{- end }}
  skrDNSProvidersValues.yaml: |-
{{- with .Values.skrDNSProvidersValues }}
{{ tpl . $ | indent 4 }}
{{- end }}
  catalog.yaml: |-
{{ tpl (.Files.Get "files/catalog.yaml") . | indent 4 }}
  freemiumWhitelistedGlobalAccountIds.yaml: |-
{{- with .Values.freemiumWhitelistedGlobalAccountIds }}
{{ tpl . $ | indent 4 }}
{{- end }}
  regionsSupportingMachine.yaml: |-
{{- with .Values.regionsSupportingMachine }}
{{ tpl . $ | indent 4 }}
{{- end }}
  hapRule.yaml: |-
    rule:
{{ toYamlPretty .Values.hap.rule | indent 4  }}
  providersConfig.yaml: |-
{{ toYamlPretty .Values.providersConfiguration | indent 4 }}
  plansConfig.yaml: |-
{{ toYamlPretty .Values.plansConfiguration | indent 4 }}
  quotaWhitelistedSubaccountIds.yaml: |-
{{- with .Values.quotaWhitelistedSubaccountIds }}
{{ tpl . $ | indent 4 }}
{{- end }}